#!/usr/bin/env python3

import __init__
import sys

from _homework_manager import fetch_homework

if len(sys.argv) < 2:
    raise SystemExit("Usage: mango fetch <assignment-id|name-keyword>")

query = " ".join(sys.argv[1:]).strip()
raise SystemExit(fetch_homework(query))
